<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BtnCheckIn</name>
   <tag></tag>
   <elementGuidId>9fed8e02-9fec-4d83-893e-e77bc8d98a14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[p[normalize-space()='CheckIn']]&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
