<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Masuk</name>
   <tag></tag>
   <elementGuidId>d401ae78-7beb-419a-80b4-4e09bfa79854</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//b[text()='Masuk']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
